# See https://developers.cloudflare.com/workers/wrangler/configuration/
# The name of your Worker. Alphanumeric values and dashes only.
name = "robot"
main = "./dist/worker.js"
workers_dev = true
# account_id = ""
# route = ""
# usage_model = "bundled"
# A date in the form yyyy-mm-dd, which will be used to determine
# which version of the Workers runtime is used.
compatibility_date = "2022-08-01"
compatibility_flags = []

[build]
# command = "pnpm run build"
cwd = "./src"
watch_dir = "./src"

[[rules]]
type = "ESModule"
globs = ["**/*.js"]
